name: Add User

on:
  issues:
    types: [opened, reopened]


jobs:
  add_user:
    runs-on: ubuntu-latest

    steps:
      - name: Add User
        uses: tgrall/action-user-org-registration@main
        with:
          github_token : ${{ secrets.API_CALLS }}
          github_user : ${{ github.actor }}
          github_organization : ${{ github.repository_owner }}
          

      - name: " 🔖  Update issue"
        if: ${{ github.event.issue}}  
        uses: actions/github-script@v6.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `👋 Invitation sent to @${{ github.actor }}`
            })          
