name: Add User

on:
  issues:
    types: [opened, reopened]


jobs:
  add_user:
    runs-on: ubuntu-latest

    steps:
      - name: Add User
        uses: tgrall/action-user-org-registration@main
        with:
          github_token : ${{ github.token }}
          github_user : ${{ github.actor }}
          github_organization : ${{ github.repository_owner }}
          
